import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / 'upstream' / 'social-app'

class SocialAppWiringTests(unittest.TestCase):
    def test_following_settings_expose_local_toggle(self):
        source = (ROOT / 'src/screens/Settings/FollowingFeedPreferences.tsx').read_text()
        self.assertIn('Use local feed reranking', source)
        self.assertIn('setLocalFeedEnabled', source)

    def test_feed_pipeline_passes_local_preferences_and_explanations(self):
        page = (ROOT / 'src/view/com/feeds/FeedPage.tsx').read_text()
        feed = (ROOT / 'src/view/com/posts/PostFeed.tsx').read_text()
        item = (ROOT / 'src/view/com/posts/PostFeedItem.tsx').read_text()
        self.assertIn('localFeedPreferences', page)
        self.assertIn('rankLocallyWithTrace', feed)
        self.assertIn('Why this post?', item)

    def test_deployment_feed_is_distinct_from_bluesky_discover(self):
        constants = (ROOT / 'src/lib/constants.ts').read_text()
        feed = (ROOT / 'src/state/queries/feed.ts').read_text()
        fallback = (ROOT / 'src/view/com/posts/DiscoverFallbackHeader.tsx').read_text()
        self.assertIn("'social-discover'", constants)
        self.assertIn("displayName: 'Discover'", feed)
        self.assertIn('text="Discover"', fallback)
        self.assertNotIn('aaalbyp4zfz3s', constants)
        self.assertNotIn('aaagh476unqpu', constants)

    def test_new_accounts_start_neutral_and_custom_state_is_account_scoped(self):
        personalization = (ROOT / 'src/lib/personalization.ts').read_text()
        local_feed = (ROOT / 'src/state/preferences/local-feed.tsx').read_text()
        selected_feed = (ROOT / 'src/state/shell/selected-feed.tsx').read_text()
        settings = (ROOT / 'src/screens/Settings/PersonalizationSettings.tsx').read_text()
        navigation = (ROOT / 'src/Navigation.tsx').read_text()
        english_catalog = (ROOT / 'src/locale/locales/en/messages.po').read_text()
        self.assertIn('radlibCuration: defaultLocalCurationConfig', personalization)
        self.assertIn('contentFilterPolicy: defaultContentFilterPolicy', personalization)
        self.assertIn("PERSONALIZATION_STORAGE_PREFIX + accountDid", personalization)
        self.assertIn('setState(createDefaultLocalFeedState())', local_feed)
        self.assertIn("SESSION_FEED_KEY_PREFIX = 'lastSelectedHomeFeed:'", selected_feed)
        self.assertIn('sessionFeedKey(accountDid)', selected_feed)
        self.assertIn("Feed customization & data", settings)
        curation = (ROOT / 'src/lib/feed-sovereignty/radlib-curation.ts').read_text()
        self.assertIn('curationTerms', curation)
        self.assertIn('curationTerms: []', curation)
        self.assertIn('Local curation terms · explicit terms only', settings)
        self.assertIn('function EntryRow', settings)
        self.assertIn('Add a term to prioritize', settings)
        self.assertIn('buttonLabel="Add term"', settings)
        self.assertIn('onSubmitEditing={onSubmit}', settings)
        self.assertIn('shape="rectangular"', settings)
        self.assertIn('disabled={!enabled}', settings)
        self.assertIn('accessibilityLiveRegion="polite"', settings)
        self.assertIn('Add a local curation exclusion', settings)
        self.assertNotIn('RADLIB_CURATION_BRANCHES', settings)
        self.assertNotIn('branchActivationTerms', curation)
        self.assertNotIn('RADLIB_CURATION_EXCLUDED_TERMS', curation)
        self.assertNotIn('RadlibCurationBranch', curation)
        self.assertNotIn("'kpop'", curation)
        content_filter = (ROOT / 'src/lib/feed-sovereignty/content-filter.ts').read_text()
        self.assertNotIn('TERM_PACKS', content_filter)
        self.assertNotIn('communist-authoritarian', content_filter)
        self.assertNotIn('progressive-politics', content_filter)
        self.assertNotIn('K-pop and music', settings)
        self.assertNotIn('Audio science', settings)
        self.assertIn("title: title(msg`Feed customization & data`)", navigation)
        self.assertIn('msgid "Services"', english_catalog)
        self.assertIn('msgstr "Services"', english_catalog)
        self.assertIn('msgid "Feed customization & data"', english_catalog)
        self.assertIn('msgstr "Feed customization & data"', english_catalog)

    def test_appview_provider_selection_is_persisted_and_explicit(self):
        schema = (ROOT / 'src/state/persisted/schema.ts').read_text()
        providers = (ROOT / 'src/state/session/providers.ts').read_text()
        core = (ROOT / 'src/state/session/session-core.ts').read_text()
        clients = (ROOT / 'src/state/session/clients.ts').read_text()
        self.assertIn('appviewProviders', schema)
        self.assertIn('appviewSelections', schema)
        self.assertIn('selectAppViewProvider', providers)
        self.assertIn('registerAppViewProvider', providers)
        self.assertIn('switchAppViewProvider', core)
        self.assertIn('provider.endpoint', clients)
        self.assertIn('provider.serviceDid', clients)
        self.assertIn('switchAppViewProvider: switchAppView', (ROOT / 'src/state/session/index.tsx').read_text())
        self.assertIn('not a safe HTTPS origin', providers)
        self.assertIn("redirect: 'error'", clients)
        self.assertIn('AbortSignal.timeout(15_000)', clients)
        screen = (ROOT / 'src/screens/Settings/ServicesSettings.tsx').read_text()
        self.assertIn('Use ${candidate.displayName}', screen)
        self.assertIn('New reads will use ${provider.displayName}', screen)
        self.assertIn('No provider was substituted.', screen)
        self.assertIn('Cancel', screen)
        self.assertIn('appviewProviders: z.array(appviewProviderSchema).optional()', schema)
        self.assertIn('appviewSelections: z.record(z.string(), z.string()).optional()', schema)
        self.assertIn('appviewFallbacks', schema)
        self.assertIn('getAppViewFallback', providers)
        self.assertIn('project-appview', schema)
        self.assertIn('PersonalizationSettings', (ROOT / 'src/Navigation.tsx').read_text())
        personalization = (ROOT / 'src/lib/personalization.ts').read_text()
        self.assertIn('PERSONALIZATION_FORMAT', personalization)
        self.assertIn('encryptPersonalization', personalization)
        self.assertIn('resetLearnedState', personalization)
        local_feed = (ROOT / 'src/state/preferences/local-feed.tsx').read_text()
        self.assertIn('PERSONALIZATION_STORAGE_PREFIX', personalization)
        self.assertIn('accountDid', local_feed)
        self.assertIn('loadPersonalization', local_feed)
        self.assertNotIn('exportPersonalization', clients)
        self.assertIn("'appview-selection'", providers)

    def test_production_web_shell_uses_root_relative_assets(self):
        build_script = (ROOT / 'scripts/post-web-build.js').read_text()
        self.assertIn('Normalized static asset URLs', build_script)
        index = ROOT / 'web-build/index.html'
        if not index.exists():
            self.skipTest('production web export has not been built')
        html = index.read_text()
        self.assertNotRegex(html, r'(?:src|href)="(?!/|[a-z][a-z0-9+.-]*:|#)[^"]+"')
if __name__ == '__main__':
    unittest.main()
